titles = {
    1 : { 1 : "Johnny Bravo / Jungle Boy in Mr. Monkeyman / Johnny Bravo and the Amazon Women",
          2 : "Super Duped / Bungled in the Jungle / Bearly Enough Time!",
          3 : "The Sensitive Male! / Bravo Dooby-Doo",
          4 : "Date with an Antelope / Did You See a Bull Run By Here? / Cookie Crisis",
          5 : "I Used To Be Funny / My Fair Dork / Twas the Night",
          6 : "Blarney Buddies / Over the Hump! / Johnny Meets Farrah Fawcett",
          7 : "Hip Hop Flop / Talk to Me, Baby / Blanky Hanky Panky",
          8 : "Beach Blanket Bravo / The Day the Earth Didn't Move Around Very Much / The Aisle of Mixed-Up Toys",
          9 : "Substitute Teacher / A Wolf in Chick's Clothing / Intensive Care",
          10: "Jumbo Johnny / The Perfect Gift / Bravo, James Bravo",
          11: "Going Batty / Berry the Butler / Red Faced in the White House",
          12: "The Man who Cried Clown / Johnny Real Good / Little Talky Tabitha!",
          13: "Johnny Bravo Meets Adam West! / Under the Big Flop / Johnny Meets Donny Osmond"
          },
    2 : { 1 : "Bikini Space Planet! / Moby Jerk / A Gel for Johnny",
          2 : "Johnny Get Your Tutu / Johnny's Inferno / Forest Chump",
          3 : "Karma Krisis / A Star is Bruised / The Prince and the Pinhead",
          4 : "Claws / To Helga and Back / Cover Boy",
          5 : "Endless Bummer / Jailbird Johnny / Bravo 13",
          6 : "Doomates / Johnny's Telethon / Johnny's Guardian Angel",
          7 : "I, Fly / Schnook of the North / Charm School Johnny",
          8 : "Johnny and the Beanstalk / A Boy and His Bird / Ape is Enough",
          9 : "Panic in Jerky Town / Alien Confidential / Mama's New Boyfriend",
          10: "Welcome Back, Bravo / The Man with the Golden Gut / Aunt Katie's Farm",
          11: "Buffoon Lagoon / Johnny Goes to Camp / A League of his Own",
          12: "Brave New Johnny / Witless / Carl Be Not Proud",
          13: "El Bravo Magnifico / Johnny-O and Juliet / Clan of the Cave Boob",
          14: "Galaxy Boy / Damien's Day Out / Noir Johnny",
          15: "Hail to the Chump / A Fool for Sister Sara / Days of Blunder",
          16: "Pop Art Johnny / Dude Ranch Doofus / A Cake Too Far",
          17: "Look Who's Drooling / Law and Disorder / Tooth or Consequences",
          18: "The Unsinkable Johnny Bravo / Rashomoron / Free Pookey",
          19: "Good Knight Johnny / Balloon Platoon / The Clueless Kid",
          20: "Yukon Yutz / Prep School Johnny / Send in the Clones",
          21: "Loch Ness Johnny / Den Mother Johnny / Quo Doofus",
          22: "As I Lay Hiccupping / Marine Maroon / Thunder God Johnny"
          },
    3 : { 1 : "Luke Perry's Guide to Love / In the Line of Johnny / Fugitive Johnny",
          2 : "Virtual Johnny / Hold That Schmoe / Hunted!",
          3 : "Candidate Johnny / Johnny B. Badd / Air Bravo",
          4 : "Scoop Bravo / The Incredible Shrinking Johnny / Backdaft",
          5 : "The Johnny Bravo Affair / Biosphere Johnny / Spa Spaz",
          6 : "Fool for a Day / In Your Dreams / Some Like It Stupid",
          7 : "Dental Hikinks / Little Red Riding Johnny / Pouch Potato",
          8 : "Jurassic Dork / Mascot Academy / Full Metal Johnny",
          9 : "Johnny on Ice! / Robo-Mama / 20,000 Leagues Over my Head",
          10: "I Dream of Johnny / One Angry Bravo / Carnival of the Darned",
          11: "A Walk on the Stupid Side / Lone Star Bravo / Toy Boy Johnny",
          12: "The Great Bunny Book Ban / Enter the Chipmunk / Frankenbravo",
          13: "Lodge Brother Johnny / Chain Gang Johnny / Lumberjack Johnny",
          14: "Lord of the Links / Bootman / Freudian Dip",
          15: "Auteur! Auteur! / Runaway Train / A Reject Runs Through It",
          16: "The Island of Mrs. Morceau / The Color of Mustard / Third Dork from the Sun",
          17: "The Hansel & Gretel Project / I.Q. Johnny / Get Stinky!"
          },
    4 : { 1 : "Johnny Bravo Goes to Hollywood",
          2 : "Traffic Troubles / My Funny Looking Friend",
          3 : "Win an El Toro Guapo / Witch-ay Woman",
          4 : "Home Alone",
          5 : "Mini JB / Back from the Future",
          6 : "Non, Oui, Oui Pour Johnny / That's Entertainment!",
          7 : "Get Shovelized / T is for Trouble",
          8 : "Gray Matters / Double Vision",
          9 : "It's a Magical Life / The Hunk at the End of This Cartoon",
          10: "The Time of My Life / Run Johnny Run",
          11: "Wilderness Protection Program / A Page Right Out of History",
          12: "Some Walk By Night / Adam West's Date-o-Rama",
          13: "Johnny Makeover / Back on Shaq"
          }
    }
